name: base_app
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  micro_core:
  micro_app_login:
  micro_app_home:

dependency_overrides:
  micro_core:
    path: ../micro_core
  
  base_ui:
    path: ../base_ui

  micro_app_login:
    path: ../micro_login

  micro_app_home:
    path: ../micro_home

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
