name: base_app
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  micro_core:
  micro_login:
  micro_home:
  base_ui:

dependency_overrides:

  micro_core:
    git:
      url: https://github.com/gusttavovianna/micro_core.git
      ref: v1.0.0

  base_ui:
    git:
      url: https://github.com/gusttavovianna/base_ui.git
      ref: v1.0.0
      
  micro_login:
    git:
      url: https://github.com/gusttavovianna/micro_login.git
      ref: v1.0.0
      
  micro_home:
    git:
      url: https://github.com/gusttavovianna/micro_home.git
      ref: v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
